In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movie = pd.read_csv('movies.csv')

In [3]:
rating = pd.read_csv('ratings.csv')

In [15]:
movie.isnull().sum()
movie.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [16]:
rating.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [88]:
cv = CountVectorizer(tokenizer = lambda x: x.split('|'), analyzer='word')

## Rekomendasi Movies untuk Joko
#### Joko menyukai Superman vs. The Elite (2012

In [89]:
x = cv.fit_transform(movie['genres'])
print(cv.get_feature_names())
print(x.toarray())

['(no genres listed)', 'action', 'adventure', 'animation', 'children', 'comedy', 'crime', 'documentary', 'drama', 'fantasy', 'film-noir', 'horror', 'imax', 'musical', 'mystery', 'romance', 'sci-fi', 'thriller', 'war', 'western']
[[0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


In [90]:
similarityScore = cosine_similarity(x.toarray())
similarityScore

array([[1.        , 0.77459667, 0.31622777, ..., 0.4472136 , 0.        ,
        0.        ],
       [0.77459667, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.31622777, 0.        , 1.        , ..., 0.70710678, 0.        ,
        0.        ],
       ...,
       [0.4472136 , 0.        , 0.70710678, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [91]:
Joko = movie.index[movie['title'] == 'Superman vs. The Elite (2012)'][0]
Joko

9370

In [92]:
JokoMovie = list(enumerate(similarityScore[Joko]))
JokoMovie

[(0, 0.3162277660168379),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.408248290463863),
 (6, 0.0),
 (7, 0.0),
 (8, 0.7071067811865475),
 (9, 0.408248290463863),
 (10, 0.0),
 (11, 0.0),
 (12, 0.408248290463863),
 (13, 0.0),
 (14, 0.408248290463863),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.3162277660168379),
 (20, 0.0),
 (21, 0.0),
 (22, 0.408248290463863),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.408248290463863),
 (40, 0.0),
 (41, 0.408248290463863),
 (42, 0.0),
 (43, 0.0),
 (44, 0.0),
 (45, 0.3162277660168379),
 (46, 0.0),
 (47, 0.0),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.408248290463863),
 (62, 0.0),
 (63, 0.0),
 (64, 0.35355339059327373),
 (65, 0.7071067811865475),
 (66, 0.0),
 (6

In [93]:
JokoMovie = sorted(JokoMovie, key=lambda x: x[1], reverse=True)
JokoMovie

[(6260, 0.9999999999999998),
 (8637, 0.9999999999999998),
 (9370, 0.9999999999999998),
 (9570, 0.9999999999999998),
 (10167, 0.9999999999999998),
 (10277, 0.9999999999999998),
 (3789, 0.816496580927726),
 (6318, 0.816496580927726),
 (7816, 0.816496580927726),
 (8194, 0.816496580927726),
 (8568, 0.816496580927726),
 (9172, 0.816496580927726),
 (9381, 0.816496580927726),
 (9519, 0.816496580927726),
 (9654, 0.816496580927726),
 (9700, 0.816496580927726),
 (9750, 0.816496580927726),
 (9771, 0.816496580927726),
 (9850, 0.816496580927726),
 (9979, 0.816496580927726),
 (9984, 0.816496580927726),
 (10077, 0.816496580927726),
 (10224, 0.816496580927726),
 (8, 0.7071067811865475),
 (65, 0.7071067811865475),
 (176, 0.7071067811865475),
 (221, 0.7071067811865475),
 (576, 0.7071067811865475),
 (796, 0.7071067811865475),
 (936, 0.7071067811865475),
 (1033, 0.7071067811865475),
 (1211, 0.7071067811865475),
 (1279, 0.7071067811865475),
 (1608, 0.7071067811865475),
 (1750, 0.7071067811865475),
 (1786, 

# Result for Joko

In [94]:
RekomJoko = []
for i in JokoMovie[1:6]:
    RekomJoko.append(movie.iloc[i[0]])
RekomJoko = pd.DataFrame(RekomJoko)
RekomJoko

movieId                                           title  \
8637     79274               Batman: Under the Red Hood (2010)   
9370     94974                   Superman vs. The Elite (2012)   
9570     99813  Batman: The Dark Knight Returns, Part 2 (2013)   
10167   124867       Justice League: Throne of Atlantis (2015)   
10277   138104        Justice League: Gods and Monsters (2015)   

                 genres  
8637   Action|Animation  
9370   Action|Animation  
9570   Action|Animation  
10167  Action|Animation  
10277  Action|Animation

## Rekomendasi Movies untuk Widodo
#### Widodo menyukai Being Flynn (2012)

In [5]:
Widodo = movie.index[movie['title'] == 'Being Flynn (2012)'][0]
Widodo_id = movie.iloc[9411][0]
Widodo_id

95816

In [6]:
rating.head()
rating.drop(columns=['timestamp'], axis=1)

userId  movieId  rating
0            1       16     4.0
1            1       24     1.5
2            1       32     4.0
3            1       47     4.0
4            1       50     4.0
...        ...      ...     ...
105334     668   142488     4.0
105335     668   142507     3.5
105336     668   143385     4.0
105337     668   144976     2.5
105338     668   148626     4.5

[105339 rows x 3 columns]

In [7]:
ratingbaru = rating.pivot_table(columns=['movieId'],index=['userId'],values=['rating'])
ratingbaru = ratingbaru.fillna(0)
ratingbaru

rating                                                                 \
movieId 1      2      3      4      5      6      7      8      9      10       
userId                                                                          
1          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2          5.0    0.0    2.0    0.0    3.0    0.0    0.0    0.0    0.0    0.0   
3          0.0    0.0    0.0    0.0    3.0    0.0    3.0    0.0    0.0    0.0   
4          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5          4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
664        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
665        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
666        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
667        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
668        3.0    3.0    2.0    0.0    2.5    5.0    3.0    0.0    0.0    3.5   

         ...                                                                 \
movieId  ... 144482 144656 144976 146344 146656 146684 146878 148238 148626   
userId   ...                                                                  
1        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
5        ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
664      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
665      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
666      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
667      ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
668      ...    0.0    0.0    2.5    0.0    0.0    0.0    0.0    0.0    4.5   

                
movieId 149532  
userId          
1          0.0  
2          0.0  
3          0.0  
4          0.0  
5          0.0  
...        ...  
664        0.0  
665        0.0  
666        0.0  
667        0.0  
668        0.0  

[668 rows x 10325 columns]

In [12]:
dfcor = ratingbaru.corr().loc['rating']
dfcor = dfcor.fillna(0)
dfcor.head(10)

rating                                                              \
movieId    1         2         3         4         5         6         7        
movieId                                                                         
1        1.000000  0.229124  0.222062  0.079319  0.243736  0.211601  0.237869   
2        0.229124  1.000000  0.108133  0.085610  0.123400  0.182489  0.111970   
3        0.222062  0.108133  1.000000  0.145779  0.469828  0.224401  0.281310   
4        0.079319  0.085610  0.145779  1.000000  0.095993  0.136973  0.067767   
5        0.243736  0.123400  0.469828  0.095993  1.000000  0.123640  0.366064   
6        0.211601  0.182489  0.224401  0.136973  0.123640  1.000000  0.226081   
7        0.237869  0.111970  0.281310  0.067767  0.366064  0.226081  1.000000   
8        0.066370  0.035200  0.161308  0.184446  0.177667  0.004951 -0.019352   
9        0.026712  0.043333  0.188836  0.006738  0.086260  0.279029  0.182871   
10       0.156136  0.314376  0.039788  0.127035  0.052069  0.265137  0.115573   

                                       ...                                \
movieId    8         9         10      ...    144482    144656    144976   
movieId                                ...                                 
1        0.066370  0.026712  0.156136  ...  0.053224 -0.027328  0.054386   
2        0.035200  0.043333  0.314376  ...  0.082551  0.082551  0.035785   
3        0.161308  0.188836  0.039788  ... -0.011447 -0.011447  0.032102   
4        0.184446  0.006738  0.127035  ... -0.004763 -0.004763 -0.006649   
5        0.177667  0.086260  0.052069  ... -0.011947 -0.011947  0.040914   
6        0.004951  0.279029  0.265137  ...  0.068936  0.105883  0.147809   
7       -0.019352  0.182871  0.115573  ... -0.011248  0.130140  0.186369   
8        1.000000 -0.011925  0.069449  ... -0.002579 -0.002579 -0.003601   
9       -0.011925  1.000000  0.096960  ... -0.006932 -0.006932  0.047453   
10       0.069449  0.096960  1.000000  ...  0.072429  0.098554  0.090472   

                                                                               
movieId    146344    146656    146684    146878    148238    148626    149532  
movieId                                                                        
1       -0.027328  0.026201 -0.027328 -0.027328 -0.027328  0.026451 -0.027328  
2        0.082551  0.115655 -0.015020 -0.015020  0.082551  0.081235  0.082551  
3       -0.011447 -0.016037 -0.011447 -0.011447 -0.011447  0.029735 -0.011447  
4       -0.004763 -0.006673 -0.004763 -0.004763 -0.004763 -0.008250 -0.004763  
5       -0.011947 -0.016738 -0.011947 -0.011947 -0.011947  0.038672 -0.011947  
6        0.105883  0.118764 -0.017275 -0.017275  0.105883  0.109557  0.105883  
7        0.130140  0.069135 -0.011248 -0.011248  0.130140  0.139296  0.130140  
8       -0.002579 -0.003614 -0.002579 -0.002579 -0.002579 -0.004468 -0.002579  
9       -0.006932 -0.009711 -0.006932 -0.006932 -0.006932  0.151573 -0.006932  
10       0.098554  0.117160 -0.019007 -0.019007  0.098554  0.134155  0.098554  

[10 rows x 10325 columns]

In [11]:
rating[rating['movieId'] == Widodo_id]

userId  movieId  rating   timestamp
104869     668    95816     2.5  1351303077

In [13]:
# WIdodo menyukai film dgn id 95816 dan direkomendasikan film dgn rating 8
y = [95816, 8]

In [81]:
skor = dfcor['rating'][y[0]] * y[1]
skor = skor.sort_values(ascending=False)
print(skor.index[:5])

Int64Index([7086, 4801, 6898, 87660, 53038], dtype='int64', name='movieId')


In [87]:
WidodoMovie = []
for i in range(5):
    WidodoMovie.append(skor.index[:5][i])

WidodoMovie

indexWidodo = []
for i in WidodoMovie:
    indexWidodo.append(movie[movie['movieId'] == i].index[0])

indexWidodo

[5162, 3755, 5020, 9033, 7381]

# Result for Widodo

In [86]:
RekomWidodo = pd.DataFrame(movie.iloc[indexWidodo])
RekomWidodo

movieId                     title        genres
5162     7086          Pygmalion (1938)  Comedy|Drama
3755     4801  Little Foxes, The (1941)         Drama
5020     6898      Sweet Sixteen (2002)         Drama
9033    87660    Too Big to Fail (2011)         Drama
7381    53038           Red Dust (1932)         Drama